# Generated by Django 4.2.3 on 2025-01-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
